var myString;
var myNum;
var mybol;
var myVar;
var strArr;
var numArr;
var strNumTuple;
myString = 'Hello'.slice(0, 3);
myNum = 22;
mybol = true;
myVar = true;
console.log(myString);
strArr = ['Hello', 'Wolrd ', 'array'];
numArr = [1, 2, 3];
console.log(strArr);
strNumTuple = ['Hello', 4];
console.log(strNumTuple);
var myVoid = undefined;
var myNull = null;
console.log(myVoid);
